const { Message, ActionRowBuilder, ButtonBuilder, SelectMenuBuilder, EmbedBuilder } = require("discord.js")
const db = require("../../modüller/database")
const ayarlar = require("../../ayarlar.json")
module.exports = {
    name: "sor",
    aliases: ["sor", "sorusor", "soru", "soru-sor", "konubul", "konu-bul"],
    cooldown: 3,
    /**
   * @param {import("../../typedef").exportsRunCommands} param0 
   */
    async run({ sunucudb, pre, alisa, msg, args, sunucuid, prefix, hata, guild, msgMember, guildMe }) {
        const sorular = [
            "Yapmaktan en çok mutlu olduğun iyilik nedir?",
            "Daha çok ne durumlarda utangaç oluyorsun?",
            "Gizli kalacak fakat özel bir yeteneğin olacak olsa bu yetenek ne olurdu?",
            "Ailende en çok kime hayransın?",
            "Kendinde beğendiğin en güzel yeteneğin nedir?",
            "Eğitim alırken hedeflerine mi hareket edersin yoksa gittiği yere mi gidersin?",
            "Şuana kadar yaşadığın en komik olay nedir?",
            "En son ne zaman sabaha kadar uyumadın?",
            " Çevrene garip gelen davranışların nelerdir?",
            "Fal baktırır mısın ve inanır mısın?",
            "Ergenlik dönemini düşünecek olursan en komik yanın neydi?",
            "Bugüne kadar en mutlu olduğun gün ne zamandı?",
            "İlk okulda en iyi arkadaşın kimdi?",
            "İlk okul arkadaşlarınla hala görüşüyor musun?",
            "Hayvanları sever misin ve evde hayvan beslemek zor mu sence?",
            "Arkadaşlarınla dışarıya çıktığında gidilecek yeri sen mi belirlersin?",
            "Sosyal medya hesaplarından neleri takip etmeyi seversin?",
            "Karanlıktan korkar mısın ve neden?",
            "Batıl inancın var mı? Varsa nedir?",
            "Sana saçma gelen şeyler nelerdir?",
            "Hiç en iyi arkadaşına aşık oldun mu?",
            "İnsanların düşüncelerini okuyabilmek mi yoksa istediğin bedene bürünebilmek mi? ",
            "Birine bir şey söylemek için geçmişe dönme şansın var. Kime ne söylerdin?",
            "İnsanlarda en çok gıcık olduğun 3 hareket?",
            "Bir gerizekalıyla buluştuğunu nasıl anlarsın?",
            "Vücuduna iyi davranıyor musun?",
            "Biri hakkında bildiğin en saçma ve gereksiz şey?",
            "Şu an olmak istediğin yaş? Nedeni?",
            "Sevgilin hangi 3 şeyi yapsa mutlaka ayrılırsın?",
            "Kendinle bağdaştırdığın dizi/film/kitap karakteri?",
            "Bugün mutlu muydun? Nedeni?",
            "En son ne yedin?",
            "Çalışkan olduğunu düşünüyor musun?",
            "Her gün telefona max ne kadar zaman harcıyosun?",
            "10 yıl önceki haline ne mesaj göndermek isterdin?",
            "Sence gelmiş geçmiş en iyi 3 Türk dizisi?",
            "Deli gibi ağladığın bir film var mı? varsa ne?",
            "İnsanlarin yanında ağlama durumuna nasıl yaklaşıyosun? Acizlik mi sence?",
            "Dilim kesilseydi de söylemeseydim dediğin bi şey var mı?",
            "Daha önce hoşlandığın birine açıldın mı? Açıldıysan eğer karşındakinin tepkisi ne oldu?",
            "Bir dostta aradığın 3 özellik?",
            "Birine yaptığın en acımasız şey?",
            "Sevgililerin birbirlerini aşırı kıskanma ve kısıtlama durumuna nasıl bakıyosun?",
            "Sevdiğine ne diye hitap edersin?",
            "Kötü çocuk, yabancı, Karanlık lise, koredeki çatı katımdan sesleniyorum (ne bicim isim lan) vs. gibi wattpad kitapları hakkında düşüncen?",
            "Şimdiki yasadigin şehirden farklı bir yerde doğmak/ yaşamak ister miydin? İsteseydin neresi olsun isterdin?",
            "Attığın en saçma trip neydi? ve kime?",
            "Beni seviyor musun?",
            "Buradaki en yakışıklı/güzel kullanıcı dediğin birini etiketle",
            "İntihar edenlerle ilgili ne düşünüyosun? Sence güçlüler mi yoksa korkaklar mı?",
            "Diyelim ki çocuğun olucak adına ne verirsin?",
            "Çocuğun heteroseksüel olduğunu söyledi.Tepkin ne olurdu?",
            "Sizce de insanların bir şeyleri sırf moda olduğu için dinlemesi,izlemesi,giymesi mide bulandırıcı değil mi?",
            "Türkiyenin en iyi müzik grubu?",
            "Kötü olan ama yapmaktan kendinizi alıkoyamadıginiz bir huyunuz var mı? Varsa ne?",
            "Evleneceğiniz adamın/kadının ayak fetişi olduğunu öğrendiniz ne yaparsınız?",
            "İdam yasasının gelme ihtimaliyle ilgili düşüncelerin?",
            "Sence benim kötü özelliklerim neler?",
            "Sence kaç yaşında,hangi sebepten dolayı ölürsün?",
            "Türk komedi filmleri hakkında ne düşünüyorsun?",
            "En sevdiğin şarkılardan birini öner,dinleyeceğim",
            "Sence bir 10 yıl sonra ne yapıyor olursun?",
            "Burçlara inaniyor musun? Neden?",
            "Hayatın nereye gidiyor?",
            "Vücudunda beğenmediğin bir yer var mı? Neresi?",
            "Vücudunda gerçekten beğendiğin bir yerin var mı?",
            "Daha önce imrendigin insanlar oldu mu?",
            "Daha önce havalı görünmek için izlemediğin, gitmediğin, dinlemediğin bir şeyi yaptığını soyledin mi? Söylediysen yapma,niye yapiyosun bunu?",
            "En son ne zaman utandın?",
            "En son ne zaman ağladın?",
            "En son ne zaman büyük ve içten bir kahkaha attın?",
            "Sevdiğine açıldın ve sürpriz… reddedildin… ne yaparsın?",
            "Birinin fanı olma, birine aşırı hayranlık duyma ile ilgili ne düşünüyosun?",
            "Bir insanın gerizekalı olduğunu gösteren bir takım özellikler,detaylar,sözler falan?",
            "Duymaktan en çok nefret ettiğiniz 3 kelime?",
            "Ağladığın en saçma şey?",
            "Herhangi bir suça karıştın mı?",
            "En büyük pişmanlığın nedir?",
            "Senin için bu hayatta en önemli şey nedir?",
            "Kendine ait özlü söz var mı?",
            "Bugüne kadar başardığın en büyük başarı nedir?",
            "Şimdiye kadar aldığın en zor ve seni üzen karar ne idi?",
            "Bir noktalama işareti olsan hangisi olurdun ve neden ?",
            "Aynı anda iki kişiyi sevdiğin oldu mu?",
            "Zor durumda kaldığında buradan ilk kimi ararsın?",
            "Buradaki en iyi arkadaşın kim ve neden en iyi arkadaşın?",
            "Çok fazla arkadaş edinir misin?",
            "Yapmaktan zevk aldığın bir hobin var mı?",
            "Sence dünyayı gezmek mi yoksa, 1.000.000 dolar mı?",
            "Zamanı durdurabilsen ilk ne yapardın?",
            "Kendinde sevmediğin huy nedir?",
            "Evlendiğinde düğününde en çok görmek istediğin arkadaşın kim?",
            "Uzun süredir görüşmediğin ama gerçek dostum dediğin biri var mı?",
            "Soğuk espri yapar mısın?",
            "Neden bunu biliyorum dediğin bir bilgiyi paylaşır mısın?",
            "Eski sevgililerinle konuşur musun bazen?",
            "Yabancı dizi izliyor musun?",
            "En çok hangini diziyi seviyorsun?",
            "En sevdiğin renk?",
            "Bugün en çok ihtiyaç duyduğun şey nedir?",
            "Saç sitilini hangi sıklıkla değiştirirsin?",
            "Tanımadığın insanların sana soru sorması ve onları cevaplaman nasıl bir duygu?",
            "İlk bilgisayarına sahip olduğunda kaç yaşındaydın?",
            "Sana en son verilen hediye neydi?",
            "Bir erkeğin en sevmediğin yanı nedir?",
            "Yağmurlu bir günde neyi yapmayı seversin?",
            "Seni herkesten daha iyi tanıyan kişi kimdir?",
            "En son ne zaman kızgın olmuştun? Ne olmuştu?",
            "Senin için aşk ne ifade ediyor?",
            "Senin hakkında ne dedikodular var?",
            "Günde genellikle kaç telefon görüşmesi yapıyorsun?",
            "Her zaman en favori komedi filmin hangisidir?",
            "Güzel bir akşam yemeği partisi planlıyorsun ama sadece 3 kişi çağırabilirsin. Kimleri çağırırdın?",
            "İnsanlarının başkalarına söylediği en popüler yalan nedir?",
            "Sıcağı mı seversin yoksa soğuğumu?",
            "Fikirleriniz ve karakteriniz uyuşmuyor olsa da birine aşık olabilir misin?",
            "Düşmanın çok zor bir durumda kalsa ona yardım eli uzatır mıydın?",
            "Günde kaç fincan kahve içersin?",
            "Online oyun oynar mısın?",
            "Şuana kadar en sinirli olduğun an hangi neydi?",
            " Hayatında öncelik sırası kime aittir? Aile? Sevgili? Dost?",
            "Kendinde hiç sevmediğin ve değiştirmek istediğin karakter özelliğin var mı?",
            "Sence normal ve uyumlu olmak mı daha iyi, yoksa orijinal ve asi biri olmak mı?",
            "Fikirleriniz ve karakteriniz hiç uyuşmuyor olsa da bir kadına sırf güzel olduğu için aşık olabilir misin?",
            "Çok güvendiğin birinin arkandan konuştuğunu öğrensen ilk tepkin ne olurdu?",
            "Seni aldatan birini affedebilir misin?",
            "İlişkini kurtarmak için yalan söyler misin?",
            "Kendinde eksik bulduğun yönler neler?",
            "''Şimdiki aklım olsa bunu asla yapmazdım'' dediğin şeyler var mı?",
            "Hiç insanlara haksızlık ettiğini düşündüğün oldu mu?",
            "Yalan söyleme alışkanlığın var mı?",
            "Hiç uyanmak istemediğin bir rüya oldu mu?",
            "En çok gecemi yosa gündüz mü uyumayı seversin",
            "Hiç bir yalanı savundun mu?",
            "Çok sevdiğin biri senden nefret etse ne yapardın?",
            "Hangi sporu yapmaktan zevk alıyorsun?",
            "Günde kaç saat uyursun?",
            "En sevdiğin rüyayı anlatır mısın?",
            "Kendini başka birinin yerine koysaydın, kendini nasıl eleştirirdin?",
            "En çok kullandığın kelime nedir?",
            "Hiç istemeyerek verdiğin kararlar oldu mu?",
            "Düzeltmek istediğin bir yanlışın ya da hatan var mı?",
            "En iyi arkadaşın sevgiline aşık olsa ne yapardın?",
            "Hangi tarihte yaşamayı isterdin?",
            "Şuana kadar yaşadığın en güzel şey nedir?",
            "Hatırlamak istemediğin bir anın var mı?",
            "Hangi ülkede yaşamak isterdin?",
            "Aynı anda iki kişiyi sever misin?",
            "Zor durumda kaldığında ilk kimi ararsın?",
            "En iyi arkadaşın kim ve neden en iyi arkadaşın?",
            "Çok fazla arkadaş edinir misin?",
            "Evliliğe karşı düşüncelerin nedir?",
            "Yapmaktan en çok zevk aldığın şey nedir?",
            "Sence dünyayı gezmek mi yoksa, 1.000.000 dolar mı?",
            "Zamanı geri alabilsen hangi anına gitmek isterdin?",
            "Kendinde sevmediğin huy nedir?",
            "Evlendiğinde düğününde en çok görmek istediğin arkadaşın kim?",
            "Uzun süredir görüşmediğin ama gerçek dostum dediğin biri var mı?",
            "Dedikodu yapmayı sever misin? Bu konudaki düşüncen nedir?",
            "İnsanları tuhaf bulduğun oluyor mu?",
            "Teknoloji ile aran nasıl?",
            "Marka takıntın var mı?",
            "Hangi yemekleri seversin?",
            "Mangal mı? Burger'mi?",
            "İnsanlarla iletişimin nasıldır?",
            "Seni çok sıkan biri olduğunda onu nazikçe uyarır mısın yoksa sertçe çıkışır mısın?",
            "Hiç kayboldun mu?",
            "Çocukluktan gelen bir korkun var mı?",
            "Hangi durumlarda kendini kötü hissedersin?",
            "Yanında olmak istediğin biri var mı?",
            "Gelecek için planların var mı? Nelerdir?",
            "Bir çizgi film kahramanı olmak isteseydin hangisi olurdun? ",
            "Hangi gezegende yaşamak isterdin? ",
            "Özel yeteneklere sahip biri olsaydın yeteneklerini toplum için mi kullanırdın kendi çıkarların için mi? ",
            "On günlüğüne yurt dışına çıkıyorsun ve yanına 3 eşya alma hakkın var? Ne alırd,ın?",
            "Aşk tek kişilik midir yoksa insan kalbinde, aynı anda iki kişiye yer verebilir mi? ",
            "Hayatında öncelik sırası kime aittir? Aile? Sevgili? Dost?",
            "En sevdiğiniz dinozor hangisi?",
            "Hey, biraz para alabilir miyim?",
            "Sesleri de duyuyor musunuz?",
            "Hayatınızın geri kalanında yalnızca bir yemek yiyebilseydiniz, bu ne olurdu?",
            "Hangi komplo teorilerine inanıyorsunuz?",
            "Bir ejderhaya sahip olmayı mı yoksa ejderha olmayı mı tercih edersiniz?",
            "Telefon şifrenizi sevgilinizle olan yıl dönümü tarihini koyar mıydın?",
            "Gerçekleştirdiğiniz rastgele iyilik davranışlarıyla övünüyor musunuz?",
            "Şu andan itibaren, öleceksen son vasiyetinde buradakilerden kime ne bırakırdın?",
            "Şüphelendiğiniz veya sizden hoşlanmadığını tanıdığınız birini düşünün. Senin hakkında ne düşündüklerini sanıyorsun?",
            " Ölüm koğuşunda olsaydınız, son yemeğiniz ne olurdu?",
            "Zombi istilası var! Solundaki nesne ile savaşmalısın. Solunda ne var?",
            "Sen kimsin ve neden benim evimdesin?",
            "Hayatınızın geri kalanında sadece brokoli ile beslenmeyi mi tercih edersin yoksa asla pizza yememeyi mi?",
            "İlk ve son kez yaptığınız şey nedir?",
            "En sevdiğiniz koku nedir?",
            "Bir daha asla uyumama ya da bir daha asla yemek yememe seçeneğiniz olsaydı, hangisini seçerdiniz? Neden?",
            "Yemek olsaydın ne olurdun?",
            "Hangi çizgi film şarkısını seçersin",
            "Sıkıldığında ilk yaptığınız şey nedir?",
            "Dünyadaki en sevdiğin hayvan nedir?",
            "Dünyadan sonsuza kadar bir rengi çıkarmak zorunda olsaydın, bu hangisi olurdu?",
            "Kimseye belli etmediğin bir karakter özelliğini söyler misin?"
        ]
        msg.reply({ content: sorular[Math.floor(Math.random() * sorular.length)] }).catch(err => { })
    }
}
